on: [push, pull_request]

name: Run tests

jobs:
  test:
    strategy:
      matrix:
        browser:
          - "--chrome"
          - "--firefox"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - run: wasm-pack test --headless ${{ marix.browser }}
